name: Node CI
on:
  push:
    branches:
      - '**'
    tags:
      - 'v**'
  workflow_dispatch:

jobs:
  run-yarn-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: yarn install
        run: yarn install --check-files --frozen-lockfile

      - name: yarn validate:dependencies
        run: yarn validate:dependencies

      - name: yarn build
        run: yarn build

      - name: yarn unit test 
        run: yarn unit

      - name: yarn install production
        run: yarn install --check-files --frozen-lockfile --production --force

      - uses: actions/upload-artifact@main
        with:
          name: dist artifacts
          path: dist

  dockerhub-release:
    runs-on: ubuntu-latest
    needs: [run-yarn-build]
    if: | 
      ((github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop') ||  
      startsWith(github.ref, 'refs/tags/v')) &&
      github.event_name != 'pull_request'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: "tv2media/${{ github.event.repository.name }}"
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker image tags
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}